import codecs

filepath = r'C:\Users\murat\source\repos\GMK360\GMK360.Data\Contexts\ApplicationDbContext.cs'
with codecs.open(filepath, 'r', 'utf-8-sig') as f:
    content = f.read()

old_cities = '''                new City { Id = 34, CountryId = 1, Name = "?stanbul", PlateCode = "34", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 6, CountryId = 1, Name = "Ankara", PlateCode = "06", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 35, CountryId = 1, Name = "?zmir", PlateCode = "35", CreatedAt = new System.DateTime(2024, 1, 1) }'''

new_cities = '''                new City { Id = 1, CountryId = 1, Name = "Adana", PlateCode = "01", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 2, CountryId = 1, Name = "Adıyaman", PlateCode = "02", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 3, CountryId = 1, Name = "Afyonkarahisar", PlateCode = "03", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 4, CountryId = 1, Name = "Ağrı", PlateCode = "04", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 5, CountryId = 1, Name = "Amasya", PlateCode = "05", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 6, CountryId = 1, Name = "Ankara", PlateCode = "06", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 7, CountryId = 1, Name = "Antalya", PlateCode = "07", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 8, CountryId = 1, Name = "Artvin", PlateCode = "08", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 9, CountryId = 1, Name = "Aydın", PlateCode = "09", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 10, CountryId = 1, Name = "Balıkesir", PlateCode = "10", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 11, CountryId = 1, Name = "Bilecik", PlateCode = "11", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 12, CountryId = 1, Name = "Bingöl", PlateCode = "12", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 13, CountryId = 1, Name = "Bitlis", PlateCode = "13", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 14, CountryId = 1, Name = "Bolu", PlateCode = "14", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 15, CountryId = 1, Name = "Burdur", PlateCode = "15", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 16, CountryId = 1, Name = "Bursa", PlateCode = "16", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 17, CountryId = 1, Name = "Çanakkale", PlateCode = "17", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 18, CountryId = 1, Name = "Çankırı", PlateCode = "18", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 19, CountryId = 1, Name = "Çorum", PlateCode = "19", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 20, CountryId = 1, Name = "Denizli", PlateCode = "20", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 21, CountryId = 1, Name = "Diyarbakır", PlateCode = "21", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 22, CountryId = 1, Name = "Edirne", PlateCode = "22", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 23, CountryId = 1, Name = "Elazığ", PlateCode = "23", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 24, CountryId = 1, Name = "Erzincan", PlateCode = "24", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 25, CountryId = 1, Name = "Erzurum", PlateCode = "25", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 26, CountryId = 1, Name = "Eskişehir", PlateCode = "26", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 27, CountryId = 1, Name = "Gaziantep", PlateCode = "27", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 28, CountryId = 1, Name = "Giresun", PlateCode = "28", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 29, CountryId = 1, Name = "Gümüşhane", PlateCode = "29", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 30, CountryId = 1, Name = "Hakkari", PlateCode = "30", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 31, CountryId = 1, Name = "Hatay", PlateCode = "31", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 32, CountryId = 1, Name = "Isparta", PlateCode = "32", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 33, CountryId = 1, Name = "Mersin", PlateCode = "33", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 34, CountryId = 1, Name = "İstanbul", PlateCode = "34", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 35, CountryId = 1, Name = "İzmir", PlateCode = "35", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 36, CountryId = 1, Name = "Kars", PlateCode = "36", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 37, CountryId = 1, Name = "Kastamonu", PlateCode = "37", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 38, CountryId = 1, Name = "Kayseri", PlateCode = "38", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 39, CountryId = 1, Name = "Kırklareli", PlateCode = "39", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 40, CountryId = 1, Name = "Kırşehir", PlateCode = "40", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 41, CountryId = 1, Name = "Kocaeli", PlateCode = "41", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 42, CountryId = 1, Name = "Konya", PlateCode = "42", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 43, CountryId = 1, Name = "Kütahya", PlateCode = "43", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 44, CountryId = 1, Name = "Malatya", PlateCode = "44", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 45, CountryId = 1, Name = "Manisa", PlateCode = "45", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 46, CountryId = 1, Name = "Kahramanmaraş", PlateCode = "46", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 47, CountryId = 1, Name = "Mardin", PlateCode = "47", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 48, CountryId = 1, Name = "Muğla", PlateCode = "48", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 49, CountryId = 1, Name = "Muş", PlateCode = "49", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 50, CountryId = 1, Name = "Nevşehir", PlateCode = "50", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 51, CountryId = 1, Name = "Niğde", PlateCode = "51", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 52, CountryId = 1, Name = "Ordu", PlateCode = "52", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 53, CountryId = 1, Name = "Rize", PlateCode = "53", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 54, CountryId = 1, Name = "Sakarya", PlateCode = "54", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 55, CountryId = 1, Name = "Samsun", PlateCode = "55", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 56, CountryId = 1, Name = "Siirt", PlateCode = "56", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 57, CountryId = 1, Name = "Sinop", PlateCode = "57", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 58, CountryId = 1, Name = "Sivas", PlateCode = "58", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 59, CountryId = 1, Name = "Tekirdağ", PlateCode = "59", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 60, CountryId = 1, Name = "Tokat", PlateCode = "60", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 61, CountryId = 1, Name = "Trabzon", PlateCode = "61", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 62, CountryId = 1, Name = "Tunceli", PlateCode = "62", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 63, CountryId = 1, Name = "Şanlıurfa", PlateCode = "63", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 64, CountryId = 1, Name = "Uşak", PlateCode = "64", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 65, CountryId = 1, Name = "Van", PlateCode = "65", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 66, CountryId = 1, Name = "Yozgat", PlateCode = "66", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 67, CountryId = 1, Name = "Zonguldak", PlateCode = "67", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 68, CountryId = 1, Name = "Aksaray", PlateCode = "68", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 69, CountryId = 1, Name = "Bayburt", PlateCode = "69", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 70, CountryId = 1, Name = "Karaman", PlateCode = "70", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 71, CountryId = 1, Name = "Kırıkkale", PlateCode = "71", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 72, CountryId = 1, Name = "Batman", PlateCode = "72", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 73, CountryId = 1, Name = "Şırnak", PlateCode = "73", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 74, CountryId = 1, Name = "Bartın", PlateCode = "74", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 75, CountryId = 1, Name = "Ardahan", PlateCode = "75", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 76, CountryId = 1, Name = "Iğdır", PlateCode = "76", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 77, CountryId = 1, Name = "Yalova", PlateCode = "77", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 78, CountryId = 1, Name = "Karabük", PlateCode = "78", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 79, CountryId = 1, Name = "Kilis", PlateCode = "79", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 80, CountryId = 1, Name = "Osmaniye", PlateCode = "80", CreatedAt = new System.DateTime(2024, 1, 1) },
                new City { Id = 81, CountryId = 1, Name = "Düzce", PlateCode = "81", CreatedAt = new System.DateTime(2024, 1, 1) },
'''

content = content.replace(old_cities, new_cities.strip())

with codecs.open(filepath, 'w', 'utf-8-sig') as f:
    f.write(content)
