BEGIN TRY
    ALTER TABLE SystemLegalDocumentTemplates ADD DisplayOrder INT NOT NULL DEFAULT 0;
END TRY BEGIN CATCH END CATCH

BEGIN TRY
    ALTER TABLE ProjectLegalDocuments ADD DisplayOrder INT NOT NULL DEFAULT 0;
END TRY BEGIN CATCH END CATCH

BEGIN TRY
    ALTER TABLE ProjectLegalDocuments ALTER COLUMN Status NVARCHAR(50) NULL;
END TRY BEGIN CATCH END CATCH
