ALTER TABLE B2bCompanyCategories DROP CONSTRAINT IF EXISTS FK__B2bCompan__B2bCo__6E414E4F;
ALTER TABLE B2bCompanyCategories DROP CONSTRAINT IF EXISTS FK__B2bCompan__B2bCa__6F357288;
DROP TABLE IF EXISTS B2bCompanyCategories;
DROP TABLE IF EXISTS B2bCategories;

CREATE TABLE B2bCompanyCategories (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    B2bCompanyId INT NOT NULL FOREIGN KEY REFERENCES B2bCompanies(Id) ON DELETE CASCADE,
    DefinitionValueId INT NOT NULL FOREIGN KEY REFERENCES DefinitionValues(Id) ON DELETE CASCADE,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NULL,
    IsDeleted BIT NOT NULL DEFAULT 0
);
